### ISSUE TITLE
Remove hard coding of configuration values

### ISSUE THREAD

**Issue by cwdcwd** [topcoderinc/HPE-LP-MentorMe-Services#15]
### Description:
Configuration values should be injected at build/run time from the environment and not hard coded into the codebase.  This should apply to all specific URLs, usernames, passwords, API keys, etc. 

### Requirements:
- remove hard coded values from [application.properties file](https://github.com/topcoderinc/HPE-LP-MentorMe-Services/blob/master/src/main/resources/application.properties#L2)
- inject values from environmental variables

### Submissions:
- Ensure good test coverage on all modules
- Upload documentation for how to run your submission
- Upload all your source code as a zip for review
- Winner will be required to submit a pull request with their winning code.

**Comment by cwdcwd** [comment]
@huangqun check out this ticket

**Comment by ward-appirio** [comment]
@cwdcwd It looks like we do have a command line interface for our configuration parameters implemented:  

Here is the note from the readme:  
### custom configurations using command line parameters or system variables
Please check all property keys in `src/main/resources/application.properties`.
You can custom using command line parameters or system variables easily.
For example custom server port **-Dserver.port=8087** as command line parameter or using **set server.port=8087** under windows or **export SERVER_PORT=8087** under linux.
similar for database,email related configurations.

I'm trying to find the code that would consume the command-line variables...the documentation is pretty thin.

**Comment by cwdcwd** [comment]
great. maybe we get that into the pom if it isn't in there already

**Comment by ward-appirio** [comment]
Chris,  

I've been reviewing the SpringBoot and Maven docs and it looks like we can just add any of our required system parameters right to the command line: 

https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-external-config.html
http://stackoverflow.com/questions/7513319/passing-command-line-arguments-from-maven-as-properties-in-pom-xml

So, for example, if we want to pass the database hostname and port and mail server ip to the command line it would look like the following:

mvn clean spring-boot:run "-Dspring.datasource.url=jdbc:mysql://54.212.207.211:3306/mentorme?useSSL=false" "-Dspring.mail.host=localhost" 

We should be able to leave the application.properties alone.   This can be our "default" settings and then we can override the necessary properties at the command line for system independence.  It looks like it is set up like that by design.

**Comment by cwdcwd** [comment]
good stuff. could we perhaps do it via a settings.xml file and inject the requisite settings via env vars? Check [this out](https://devcenter.heroku.com/articles/using-a-custom-maven-settings-xml#using-password-protected-repositories). If we can do that then we can simply use the Heroku deploy pipeline and have this automatically deploy as needed.
